# Generated by Django 4.0.5 on 2022-10-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoparts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryparts',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/category', verbose_name='Изображение категории'),
        ),
    ]
